version: "3.6"
services:
  nginx:
    build: ./front/nginx_conf.d
    ports:
    - '8081:80'
    depends_on:
    - front
    - waf

  front:
    build: front
    container_name: front
    restart: always

  waf:
    build: waf
    command: sh -c "/wait && node /src/app/bin/www"
    container_name: waf
    environment:
      - DB_NAME=syndore
      - DB_USER=syn_user
      - DB_PASS=syn_pass
      - JWT_SECRET=2e868949ff43700534942672b71039b9c0d2f9ec423d05c9f4ccd52ebf38261b8d4ab41d4a72b2a3fcb57f78635318741e03a4dfe80083f6f14371d768a7d48d
      - DB_HOST=database
      - WAIT_HOSTS=database:3306, backend:3000
      - WAIT_BEFORE=30
      - WAIT_TIMEOUT=300
      - WAIT_HOST_CONNECT_TIMEOUT=10

  backend:
    build: api
    command: sh -c "/wait && node /src/app/bin/www"
    container_name: backend
    environment:
      - DB_NAME=syndore
      - DB_USER=syn_user
      - DB_PASS=syn_pass
      - JWT_SECRET=2e868949ff43700534942672b71039b9c0d2f9ec423d05c9f4ccd52ebf38261b8d4ab41d4a72b2a3fcb57f78635318741e03a4dfe80083f6f14371d768a7d48d
      - DB_HOST=database
      - WAIT_HOSTS=database:3306
      - WAIT_BEFORE=30
      - WAIT_TIMEOUT=300
      - WAIT_HOST_CONNECT_TIMEOUT=10

  database:
    platform: linux/x86_64
    container_name: database
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=syndore
      - MYSQL_USER=syn_user
      - MYSQL_PASSWORD=syn_pass

volumes:
  db_data:
